export const INITIAL_MEDICINES = [
    { name: "Rhinathiol Tusso 100 mg tabletta", price: 2389, description: "A Rhinathiol Tusso tabletta száraz köhögés csillapítására szolgáló készítmény, amely megkönnyíti a légzést és a köpet mennyiségét is befolyásolja." },
    { name: "Paracetamol 500 mg tabletta", price: 1099, description: "A Paracetamol tabletta lázcsillapításra és fájdalomcsillapításra szolgál." },
    { name: "Ibuprofen 400 mg tabletta", price: 1599, description: "Az Ibuprofen tabletta gyulladáscsökkentő és fájdalomcsillapító hatású." },
    { name: "Loratadin 10 mg tabletta", price: 1899, description: "A Loratadin tabletta allergiás tünetek, például orrfolyás, tüsszögés és viszketés enyhítésére szolgál." },
    { name: "Amoxicillin 500 mg tabletta", price: 2799, description: "Az Amoxicillin tabletta bakteriális fertőzések kezelésére szolgál." },
    { name: "Dexpanthenol krém", price: 2199, description: "A Dexpanthenol krém segíthet a bőr regenerálódásában és hidratálásában." },
    { name: "Cetirizin 10 mg tabletta", price: 2099, description: "A Cetirizin tabletta allergiás tünetek enyhítésére szolgál." },
    { name: "Diclofenac 50 mg tabletta", price: 1999, description: "A Diclofenac tabletta gyulladáscsökkentő és fájdalomcsillapító hatású." },
    { name: "Dexametazon 0.5 mg tabletta", price: 3199, description: "A Dexametazon tabletta gyulladáscsökkentő és immunszuppresszív hatású." },
    { name: "Fenilefrin 5 mg tabletta", price: 2599, description: "A Fenilefrin tabletta orrfolyás és torokfájás enyhítésére szolgál." },
    { name: "Omeprazol 20 mg tabletta", price: 1999, description: "Az Omeprazol tabletta gyomorsavcsökkentő hatású, gyomorfekély kezelésére alkalmazzák." },
    { name: "Hydrocortison krém", price: 2399, description: "A Hydrocortison krém enyhítheti a bőr viszketését és gyulladását." },
    { name: "Metamizol 500 mg tabletta", price: 1799, description: "A Metamizol tabletta lázcsillapításra és fájdalomcsillapításra szolgál." },
    { name: "Mentolos torokcukor", price: 499, description: "A Mentolos torokcukor enyhítheti a torokfájást és a köhögést." },
    { name: "Echinacea cseppek", price: 2599, description: "Az Echinacea cseppek immunrendszer erősítésére szolgálnak." },
    { name: "C-vitamin 500 mg tabletta", price: 799, description: "A C-vitamin tabletta immunrendszer erősítésére szolgál." },
    { name: "Probiotikum kapszula", price: 3299, description: "A Probiotikum kapszula segíthet a bélflóra egyensúlyának fenntartásában." },
    { name: "Magnézium 250 mg tabletta", price: 1299, description: "A Magnézium tabletta segíthet a szervezet magnéziumszintjének pótlásában." },
    { name: "B-vitamin komplex tabletta", price: 1899, description: "A B-vitamin komplex tabletta segíthet az idegrendszer működésének fenntartásában." },
    { name: "Ginkgo biloba kivonat kapszula", price: 2699, description: "A Ginkgo biloba kivonat kapszula javíthatja a vérkeringést és a memóriát." },
    { name: "Glükozamin-kondroitin tabletta", price: 3499, description: "A Glükozamin-kondroitin tabletta segíthet a porckopás tüneteinek enyhítésében." },
    { name: "Foszfatidil-szerin kapszula", price: 3899, description: "A Foszfatidil-szerin kapszula segíthet a memória és a koncentráció javításában." },
    { name: "Kálcium 500 mg tabletta", price: 999, description: "A Kálcium tabletta segíthet a csontok erősítésében és a fogak egészségének fenntartásában." },
    { name: "Koenzim Q10 kapszula", price: 2999, description: "A Koenzim Q10 kapszula segíthet az energiaszint fenntartásában és a szív egészségének támogatásában." },
    { name: "Szilícium tabletta", price: 1999, description: "A Szilícium tabletta segíthet a bőr, haj és köröm egészségének fenntartásában." },
    { name: "Kurkuma kapszula", price: 1899, description: "A Kurkuma kapszula gyulladáscsökkentő hatású és segíthet az emésztésben." },
    { name: "Maca gyökér kapszula", price: 2799, description: "A Maca gyökér kapszula segíthet a szexuális teljesítmény növelésében és az energiafokozásban." },
    { name: "Szelén kapszula", price: 1799, description: "A Szelén kapszula antioxidáns hatású és segíthet az immunrendszer erősítésében." },
    { name: "D-vitamin 1000 NE tabletta", price: 1299, description: "A D-vitamin tabletta segíthet az immunrendszer erősítésében és a csontok egészségének fenntartásában." },
    { name: "Krétafű tabletta", price: 2499, description: "A Krétafű tabletta segíthet a gyomor-bélrendszer egészségének fenntartásában és a gyulladások csökkentésében." },
    { name: "Mentolos borogatás", price: 1599, description: "A Mentolos borogatás enyhítheti az izomfájdalmat és a feszültséget." },
    { name: "Lutein-karotinoid tabletta", price: 2399, description: "A Lutein-karotinoid tabletta segíthet a szem egészségének fenntartásában és a látás javításában." },
    { name: "Propolisz szirup", price: 2999, description: "A Propolisz szirup segíthet a torokfájás és a köhögés enyhítésében." },
    { name: "E-vitamin 400 NE kapszula", price: 1499, description: "Az E-vitamin kapszula antioxidáns hatású és segíthet a bőr és a haj egészségének fenntartásában." },
    { name: "Probiotikum rágótabletta", price: 2599, description: "A Probiotikum rágótabletta segíthet a bélflóra egyensúlyának fenntartásában és a gyomorpanaszok enyhítésében." },
    { name: "Kámfor krém", price: 1999, description: "A Kámfor krém enyhítheti az izomfájdalmat és a reumás panaszokat." },
    { name: "Gyömbér kapszula", price: 1799, description: "A Gyömbér kapszula segíthet a gyomorpanaszok és a hányinger enyhítésében." },
    { name: "Kelp kapszula", price: 2199, description: "A Kelp kapszula segíthet a pajzsmirigy működésének támogatásában és a hormonális egyensúly fenntartásában." },
    { name: "Omega-3 halolaj kapszula", price: 2799, description: "Az Omega-3 halolaj kapszula segíthet a szív- és érrendszer egészségének fenntartásában." },
    { name: "Teafaolaj", price: 1499, description: "A Teafaolaj segíthet a bőrproblémák, például akné és pattanások kezelésében." },
    { name: "Ginzeng kapszula", price: 2599, description: "A Ginzeng kapszula segíthet az energiaszint növelésében és a szellemi teljesítmény javításában." },
    { name: "Hialuronsav krém", price: 2999, description: "A Hialuronsav krém segíthet a bőr hidratálásában és a ráncok csökkentésében." },
    { name: "Kurkumin-komplex kapszula", price: 3199, description: "A Kurkumin-komplex kapszula gyulladáscsökkentő hatású és segíthet az ízületi panaszok enyhítésében." },
    { name: "Melatonin 5 mg tabletta", price: 1999, description: "A Melatonin tabletta segíthet az alvászavarok kezelésében és a jobb alvás elérésében." },
    { name: "Gyógynövényes szájvíz", price: 1999, description: "A Gyógynövényes szájvíz segíthet a szájüreg egészségének fenntartásában és a friss lehelet biztosításában." },
    { name: "Hársfavirágzat szirup", price: 2599, description: "A Hársfavirágzat szirup segíthet az orrdugulás és a torokfájás enyhítésében." },
    { name: "Progeszteron krém", price: 3299, description: "A Progeszteron krém segíthet a hormonális egyensúly fenntartásában és a menopauza tüneteinek enyhítésében." },
    { name: "Alkoholmentes fertőtlenítőspray", price: 1499, description: "Az Alkoholmentes fertőtlenítőspray segíthet a baktériumok és vírusok elleni védekezésben." },
    { name: "Folsav tabletta", price: 899, description: "A Folsav tabletta segíthet a terhesség alatt a megfelelő fejlődésű magzat kialakulásában." },
    { name: "Echinacea-tea", price: 899, description: "Az Echinacea-tea immunrendszer erősítésére szolgál." },
    { name: "Kámforos olaj", price: 1299, description: "A Kámforos olaj enyhítheti az izomfájdalmat és a reumás panaszokat." },
    { name: "Ginseng-tea", price: 1099, description: "A Ginseng-tea segíthet az energiaszint növelésében és a szellemi teljesítmény javításában." },
    { name: "Fogínymasszázs gél", price: 1799, description: "A Fogínymasszázs gél segíthet a fogínygyulladás enyhítésében és a fogíny egészségének fenntartásában." },
    { name: "Lábápoló krém", price: 1699, description: "A Lábápoló krém segíthet a bőr hidratálásában és a lábproblémák enyhítésében." },
    { name: "Körömvirág krém", price: 1999, description: "A Körömvirág krém segíthet a bőr regenerálódásában és a kisebb sérülések gyógyításában." },
    { name: "Gyógynövényes fürdősó", price: 1499, description: "A Gyógynövényes fürdősó segíthet a relaxációban és az izomfeszültség enyhítésében." },
    { name: "Gyógynövényes sampon", price: 1999, description: "A Gyógynövényes sampon segíthet a haj és a fejbőr egészségének fenntartásában." },
    { name: "Szibériai ginzeng kapszula", price: 2999, description: "A Szibériai ginzeng kapszula segíthet az energiaszint növelésében és a szellemi teljesítmény javításában." }
  ];
  